POST http://localhost:8081/_api/test
Content-Type: application/json

{
  "id": 1000,
  "name": "huang"
}



###
GET http://localhost:8082/user
Accept: application/json

###
GET http://localhost:8082/

###
GET http://localhost:8082/restful/user
Accept: application/json

###
GET http://localhost:8082/restful

### jap 功能设置
GET http://localhost:8081/jpa

###
GET http://localhost:8081/mybatis

###
GET http://localhost:8081/j2m